START TRANSACTION;
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('A03',1,'Mixed');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('A04',2,'Generation');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('A05',3,'Load');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B01',4,'Biomass');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B02',5,'Fossil Brown coal/Lignite');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B03',6,'Fossil Coal-derived gas');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B04',7,'Fossil Gas');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B05',8,'Fossil Hard coal');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B06',9,'Fossil Oil');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B07',10,'Fossil Oil shale');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B08',11,'Fossil Peat');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B09',12,'Geothermal');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B10',13,'Hydro Pumped Storage');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B11',14,'Hydro Run-of-river and poundage');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B12',15,'Hydro Water Reservoir');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B13',16,'Marine');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B14',17,'Nuclear');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B15',18,'Other renewable');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B16',19,'Solar');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B17',20,'Waste');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B18',21,'Wind Offshore');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B19',22,'Wind Onshore');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B20',23,'Other');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B21',24,'AC Link');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B22',25,'DC Link');
INSERT INTO mapping.entsoe_fueltype(entsoecode, fuel_id, name) VALUES('B23',26,'Substation');
COMMIT;