CREATE USER poweradmin WITH ENCRYPTED PASSWORD 'poweradmin';
CREATE DATABASE :dbname WITH ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';
ALTER DATABASE :dbname OWNER TO poweradmin;
GRANT ALL PRIVILEGES ON DATABASE :dbname TO poweradmin;
