{
 "title": "nextone Copy",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "areacode",
    "label": "areacode",
    "query": "SELECT\n  id AS __value,\n  eic || ' - ' || name AS __text\nFROM\n  common.area\nWHERE bzn = true or cta = true\nORDER BY\n  name;"
   }
  ]
 },
 "panels": [
  {
   "title": "Installed capacity per fuel type",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT \n    f.name AS fueltype,\n    SUM(p.capacity) AS total_capacity\nFROM \n    common.powerplant p\nJOIN \n    common.fueltype f ON p.fueltype = f.id\nJOIN \n    common.area a ON p.area = a.id\nWHERE \n    p.area = '${areacode}'\nGROUP BY \n    f.name\nORDER BY \n    total_capacity DESC;"
    }
   ]
  },
  {
   "title": "Generation / Fueltype",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ft.name AS \"fueltype\",         -- Fueltype dimension (for slices)\n  SUM(ag.value) AS \"value\"       -- Total generation value per fuel type\nFROM\n  area.actual_generation ag\nJOIN\n  common.fueltype ft ON ag.fueltype = ft.id\nWHERE\n  datetime BETWEEN $__timeFrom() AND $__timeTo()  -- Filter by Grafana time range macros\n  AND ag.area_id = '${areacode}'                  -- Filter by selected area\nGROUP BY\n  ft.name                                         -- Group by fuel type\nORDER BY\n  SUM(ag.value) DESC;                             -- Optional: Order by total value for better visualization"
    }
   ]
  },
  {
   "title": "Generation / Fueltype",
   "type": "timeseries",
   "description": "Generation per fueltype per selected area",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",          -- Time dimension\n  ft.name AS \"fueltype\",        -- Fueltype dimension (for series/legend)\n  SUM(ag.value) AS \"value\"      -- Aggregated generation value\nFROM\n  area.actual_generation ag\nJOIN\n  common.fueltype ft ON ag.fueltype = ft.id\nWHERE\n  datetime BETWEEN $__timeFrom() AND $__timeTo()  -- Grafana time range macros\n  AND ag.area_id = '${areacode}'                          -- Filter by area variable\nGROUP BY\n  datetime, ft.name\nORDER BY\n  datetime ASC;"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "description": "Generation per fueltype per selected area",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",          -- Time dimension\n  SUM(atl.value) AS \"Actual Total Load\"      -- Aggregated generation value\nFROM\n  area.actual_total_load atl\nWHERE\n  datetime BETWEEN $__timeFrom() AND $__timeTo()  -- Grafana time range macros\n  AND atl.area_id = '${areacode}'                          -- Filter by area variable\nGROUP BY\n  datetime\nORDER BY\n  datetime ASC;"
    }
   ]
  }
 ]
}