{
 "title": "Country Copy",
 "time": { "from": "2024-09-25T08:54:42.540Z", "to": "2025-01-23T08:54:42.544Z" },
 "templating": {
  "list": [
   {
    "name": "areacode",
    "label": "areacode",
    "query": "SELECT\n  id AS __value,\n  eic || ' - ' || name AS __text\nFROM\n  common.area\nWHERE bzn = true or cta = true\nORDER BY\n  name;"
   }
  ]
 },
 "panels": [
  {
   "type": "speakyourcode-button-panel",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "select ca.eic as \"EIC Code\", ca.name as \"Area code\", cc.\"name\" as Country \nfrom common.area ca\njoin common.country cc on ca.countrycode = cc.code\nwhere ca.id = '${areacode}'"
    }
   ]
  },
  {
   "title": "Installed capacity per fuel type",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT \n    f.name AS fueltype,\n    SUM(p.nominalpower) AS total_capacity\nFROM \n    common.powerplant p\nJOIN \n    common.fueltype f ON p.fueltype = f.id\nJOIN \n    common.area a ON p.area = a.id\nWHERE \n    p.area = '${areacode}'\nGROUP BY \n    f.name\nORDER BY \n    total_capacity ASC;"
    }
   ]
  },
  {
   "title": "Generation / Fueltype",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ft.name AS \"fueltype\",         -- Fueltype dimension (for slices)\n  SUM(ag.value) AS \"value\"       -- Total generation value per fuel type\nFROM\n  area.actual_generation ag\nJOIN\n  common.fueltype ft ON ag.fueltype = ft.id\nWHERE\n  datetime BETWEEN $__timeFrom() AND $__timeTo()  -- Filter by Grafana time range macros\n  AND ag.area_id = '${areacode}'                  -- Filter by selected area\nGROUP BY\n  ft.name                                         -- Group by fuel type\nORDER BY\n  SUM(ag.value) DESC;                             -- Optional: Order by total value for better visualization"
    }
   ]
  },
  {
   "title": "Generation / Fueltype",
   "type": "timeseries",
   "description": "Generation per fueltype per selected area",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",          -- Time dimension\n  ft.name AS \"fueltype\",        -- Fueltype dimension (for series/legend)\n  SUM(ag.value) AS \"value\"      -- Aggregated generation value\nFROM\n  area.actual_generation ag\nJOIN\n  common.fueltype ft ON ag.fueltype = ft.id\nWHERE\n  datetime BETWEEN $__timeFrom() AND $__timeTo()  -- Grafana time range macros\n  AND ag.area_id = '${areacode}'                          -- Filter by area variable\nGROUP BY\n  datetime, ft.name\nORDER BY\n  datetime ASC;"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "description": "Generation per fueltype per selected area",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",          -- Time dimension\n  SUM(atl.value) AS \"Actual Total Load\"      -- Aggregated generation value\nFROM\n  area.actual_total_load atl\nWHERE\n  datetime BETWEEN $__timeFrom() AND $__timeTo()  -- Grafana time range macros\n  AND atl.area_id = '${areacode}'                          -- Filter by area variable\nGROUP BY\n  datetime\nORDER BY\n  datetime ASC;"
    }
   ]
  },
  {
   "title": "Powerplant list",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT \n    p.name as plantname, p.eic, \n    f.name AS fueltype,\n    location_name,\n    highvoltagelimit,\n    nominalpower AS \"nomimal power\"\nFROM \n    common.powerplant p\nJOIN \n    common.fueltype f ON p.fueltype = f.id\nJOIN \n    common.area a ON p.area = a.id\nWHERE \n    p.area = '${areacode}'\nORDER BY \n    p.fueltype, p.name"
    }
   ]
  },
  {
   "title": "Geo Map",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 11, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT \n    f.name AS fueltype,\n    p.name AS \"Name\", \n    eic AS \"EIC Code\", \n    location[0] AS lat,\n    location[1] AS lon\nFROM common.powerplant p\nJOIN \n    common.fueltype f ON p.fueltype = f.id\nWHERE location IS NOT NULL\nAND p.area = '${areacode}';"
    }
   ]
  }
 ]
}