
INSERT INTO common.meteomodel (model_name) VALUES('ECMWF IFS 0.4°');
INSERT INTO common.meteomodel (model_name) VALUES('ECMWF IFS 0.25°');
INSERT INTO common.meteomodel (model_name) VALUES('ECMWF AIFS 0.25°');
INSERT INTO common.meteomodel (model_name) VALUES('CMA GRAPES Global');
INSERT INTO common.meteomodel (model_name) VALUES('BOM ACCESS Global');
INSERT INTO common.meteomodel (model_name) VALUES('GFS Seamless');
INSERT INTO common.meteomodel (model_name) VALUES('GFS Global');
INSERT INTO common.meteomodel (model_name) VALUES('GFS HRRR');
INSERT INTO common.meteomodel (model_name) VALUES('GFS GraphCast');
INSERT INTO common.meteomodel (model_name) VALUES('JMA Seamless');
INSERT INTO common.meteomodel (model_name) VALUES('JMA MSM');
INSERT INTO common.meteomodel (model_name) VALUES('JMA GSM');
INSERT INTO common.meteomodel (model_name) VALUES('DWD ICON Seamless');
INSERT INTO common.meteomodel (model_name) VALUES('DWD ICON Global');
INSERT INTO common.meteomodel (model_name) VALUES('DWD ICON EU');
INSERT INTO common.meteomodel (model_name) VALUES('DWD ICON D2');
INSERT INTO common.meteomodel (model_name) VALUES('GEM Seamless');
INSERT INTO common.meteomodel (model_name) VALUES('GEM Global');
INSERT INTO common.meteomodel (model_name) VALUES('GEM Regional');
INSERT INTO common.meteomodel (model_name) VALUES('GEM HRDPS Continental');
INSERT INTO common.meteomodel (model_name) VALUES('Météo-France Seamless');
INSERT INTO common.meteomodel (model_name) VALUES('Météo-France ARPEGE World');
INSERT INTO common.meteomodel (model_name) VALUES('Météo-France ARPEGE Europe');
INSERT INTO common.meteomodel (model_name) VALUES('Météo-France AROME France');
INSERT INTO common.meteomodel (model_name) VALUES('Météo-France AROME France HD');
INSERT INTO common.meteomodel (model_name) VALUES('ARPAE Seamless');
INSERT INTO common.meteomodel (model_name) VALUES('ARPAE COSMO 2I');
INSERT INTO common.meteomodel (model_name) VALUES('ARPAE COSMO 2I RUC');
INSERT INTO common.meteomodel (model_name) VALUES('ARPAE COSMO 5M');
INSERT INTO common.meteomodel (model_name) VALUES('MET Norway Nordic Seamless (with ECMWF)');
INSERT INTO common.meteomodel (model_name) VALUES('MET Norway Nordic');
INSERT INTO common.meteomodel (model_name) VALUES('KNMI Seamless (with ECMWF)');
INSERT INTO common.meteomodel (model_name) VALUES('KNMI Harmonie Arome Europe');
INSERT INTO common.meteomodel (model_name) VALUES('KNMI Harmonie Arome Netherlands');
INSERT INTO common.meteomodel (model_name) VALUES('DMI Seamless (with ECMWF)');
INSERT INTO common.meteomodel (model_name) VALUES('DMI Harmonie Arome Europe');
INSERT INTO common.meteomodel (model_name) VALUES('UK Met Office Seamless');
INSERT INTO common.meteomodel (model_name) VALUES('UK Met Office Global 10km');
INSERT INTO common.meteomodel (model_name) VALUES('UK Met Office UK 2km');
